name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - run: cd /
    - run: sudo apt-get update
    - run: sudo apt-get upgrade -y
    - run: sudo apt install linux-headers-$(uname -r)
    - run: sudo apt-get install -y ca-certificates musl-dev musl-tools file nano git
    - run: sudo apt-get install -y zlib1g-dev cmake make clang curl pkgconf xutils-dev libpq-dev libssl-dev librdkafka-dev 
    - run: sudo ln -s /usr/include/x86_64-linux-gnu/asm /usr/include/x86_64-linux-musl/asm 
    - run: sudo ln -s /usr/include/asm-generic /usr/include/x86_64-linux-musl/asm-generic
    - run: sudo ln -s /usr/include/linux /usr/include/x86_64-linux-musl/linux
    - run: sudo mkdir /musl
    - run: sudo wget https://github.com/openssl/openssl/archive/OpenSSL_1_1_1j.tar.gz
    - run: sudo tar zxvf OpenSSL_1_1_1j.tar.gz
    - run: cd openssl-OpenSSL_1_1_1j/
    - run: CC="musl-gcc -fPIE -pie" ./Configure no-shared no-async --prefix=/musl --openssldir=/musl/ssl linux-x86_64
    - run: sudo make depend
    - run: sudo make -j$(nproc)
    - run: sudo make install
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
